name: Deploy the application to production

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  INSTANCE_TYPE: r4.large
#  INSTANCE_TYPE: t3.large
  SECURITY_GROUP_NAME: bootiful-podcast-sg
  KEYPAIR_NAME: bootiful-podcast-kp

  PODCAST_RMQ_ADDRESS_development: ${{ secrets.PODCAST_RMQ_ADDRESS_development }}
  PODCAST_RMQ_ADDRESS_production: ${{ secrets.PODCAST_RMQ_ADDRESS_production }}

on:
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  install-processor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: test the AWS CLI
        run: aws --version && aws ec2 describe-instances

      - name: inspect
        run: cd $GITHUB_WORKSPACE && pwd  && find . && env

      - name: run deploy.sh
        run: cd $GITHUB_WORKSPACE/.github/workflows && ./deploy.sh
