---
resources:
  - deployment.yaml
  - service.yaml

namespace: development

commonLabels:
  env: development
  app: processor

secretGenerator:
  - name: processor-secrets
    envs:
      - processor-secrets.env
